### ISSUE TITLE
On cliciking on login button multiple time captcha come multiple time and need to add scroll bar or captcha should come only time

### ISSUE THREAD

**Issue by sunny2319** [arpit2444/grieving-driving-625#54]
![image](https://user-images.githubusercontent.com/40441142/219882164-7e9194e8-8a0f-4016-b1dd-183ba7435ec9.png)

**Comment by Kashif-Rezwi** [comment]
The login issue is resolved.  If someone tries to log in with an invalid number it will show a pop-up error message and if someone tries to log in with a long number then it will show a pop-up error message after that you have to close the login modal then again try with the valid number it will work.
