### ISSUE TITLE
On refreshing the page error is there.

### ISSUE THREAD

**Issue by deep1296** [arpit2444/grieving-driving-625#61]
- [ ] Resolve the error in routing.

<img width="494" alt="image" src="https://user-images.githubusercontent.com/96063026/222345498-744af759-54e1-4b4d-bb60-11f1fcd8e84f.png">

**Comment by arpit2444** [comment]
The website you are talking about, I have never built one that my netlify link is different. and you are attaching screenshot for lenskart. so, please always try to recheck before creating any issue on any public repo.

**Comment by arpit2444** [comment]
The website you are talking about, I have never built one that my netlify
link is different. and you are attaching screenshot for lenskart. so,
please always try to recheck before creating any issue on any public repo.

**Comment by deep1296** [comment]
The screenshot that I have attached was just for your reference now the correct screenshot was attached check and resolve
