### ISSUE TITLE
On refreshing the page error is there

### ISSUE THREAD

**Issue by deep1296** [arpit2444/grieving-driving-625#62]
- [ ] https://soft-custard-9f29c0.netlify.app/category

![image](https://user-images.githubusercontent.com/96063026/222345882-7a12476b-3151-4d3e-bd8f-37af9be6e624.png)

**Comment by deep1296** [comment]
Previously, The screenshot that I have attached was just for your reference now the correct screenshot is attached check and resolve.

**Comment by arpit2444** [comment]
sorry I was confused with the previous screenshot so after confirmation I  have gone through my mistake and corrected that now it's working fine. thank you.
